name: 改善要望
description: Regex-100knocksに関する改善要望などに関するお問い合わせ
title: "ENH: "
labels: [Enhancement, Needs Triage]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: 要望の種別
      description: ご要望やご提案についてあてはまるものを選んでください．
      options:
        - label: >
            Regex-100knocksに新機能を追加したい．
        - label: >
            Regex-100knocksにすでにある機能を改善したい．
        - label: >
            Regex-100knocksにすでにある機能を削除したい．
  - type: textarea
    id: description
    attributes:
      label: 現状の課題についてご記載ください．
      description: >
        
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: 改善要望について詳しくご記載ください．
      description: >
        
    validations:
      required: true